SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK_SALES C
     INNER JOIN BOOK B ON C.BOOK_ID = B.BOOK_ID
     INNER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE C.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;