SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(a.PRICE * b.AMOUNT) AS PRICE
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE TO_CHAR(b.PRODUCE_DATE, 'yyyy-mm') = '2022-05'
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY PRICE DESC, a.PRODUCT_ID;