SELECT b.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF a
    JOIN ICECREAM_INFO b
    ON a.FLAVOR = b.FLAVOR
WHERE b.INGREDIENT_TYPE = 'sugar_based'
    OR b.INGREDIENT_TYPE = 'fruit_based'
GROUP BY INGREDIENT_TYPE
ORDER BY a.TOTAL_ORDER;