SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE A.CATEGORY = CATEGORY)
AND CATEGORY IN ('과자','국','김치','식용유')
ORDER BY PRICE DESC;